import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';

class terms extends StatefulWidget {
  const terms({super.key});

  @override
  State<terms> createState() => _termsState();
}

class _termsState extends State<terms> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        centerTitle: true,
        title: Text('Terms & Conditions'),
      ),
      body: Center(
          child: SingleChildScrollView(
        child: Column(
          children: [
            SizedBox(
              height: 10,
            ),
            Container(
              height: 2400,
              width: 350,
              color: Colors.white,
              margin: EdgeInsets.all(10),
              child: Text(
                  "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.\n\nThis document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.mi.com/in website.\n\nThe domain name www.mi.com (hereinafter referred to as ) is owned by Xiaomi Singapore Pte. Limited, a company incorporated under the laws of Singapore with registration no. 201334380Z having its registered office at 81 Highgate Crescent, Singapore.\n\nYour use of the Website and services and tools are governed by the following terms and conditions  as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If You transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with Xiaomi Technology India Private Limited (hereinafter referred to as “Xiaomi”) and these terms and conditions including the policies constitute Your binding obligations, with Xiaomi.\n\nFor the purpose of these Terms of Use, wherFor the purpose of these Terms of Use, wherever the context so requires shall mean any natural or legal person who has agreed to become a buyer on the Website by providing registration data while registering on the Website as registered user using the computer systems. Xiaomi also allows the User to surf the Website or making purchases without registering on the Website. The term shall mean Xiaomi Technology India Private Limited.\n\nWhen You use any of the services provided by Us through the Website, including but not limited to, (e.g. product reviews, seller reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates/changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.\n\nACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Xiaomi Policies (“Policies”) ((including but not limited to Privacy Policy available on https://www.mi.com/in/about/privacy/ as amended from time to time.\n\nMembership EligibilityUse of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. If you are a minor i.e. under the age of 18 years, you shall not register as a User of the Website and shall not transact on or use the Website. As a minor if you wish to use or transact on the Website, such use or transaction may be made by your legal guardian or parents on the Website. Xiaomi reserves the right to terminate your membership and/or refuse to provide you with access to the Website if it is brought to Xiaomi's notice or if it is discovered that you are under the age of 18 years.\n\nMembership on the Website is free for buyers. Xiaomi does not charge any fee for browsing and buying on the Website (“Fee Policy”). Xiaomi reserves the right to change its Fee Policy from time to time. Xiaomi reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Website and such changes shall automatically become effective immediately after they are posted on the Website. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to Xiaomi Technology India Private Limited.\n\nYour Account and Registration ObligationsIf You use the Website, You shall be responsible for maintaining the confidentiality of your display name and password and You shall be responsible for all activities that occur under your display name and password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.Limitation of Liability\n\nIN NO EVENT SHALL XIAOMI BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE, EVEN IF USER HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.\n\nContact Us\n\nPlease contact us for any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Website.\n\nGrievance officer\n\nIf you have any concerns regarding the collection, retention, transfer and storage of your data please contact:\n\nGrievance Officer\n\nXiaomi Technology India Pvt Ltd, Ground Floor, AKR Infinity, Kudlu Gate, Krishna Reddy Industrial Area, Hosapalaya, Muneshwara Nagar, Bengaluru, Karnataka 560068, India\n\nEmail: grievance.officer@xiaomi.com"),
            ),
            SizedBox(
              height: 10,
            ),
          ],
        ),
      )),
    );
  }
}
